name: Bump version

on:
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: read

jobs:
  bump-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Draft release
        id: draft
        uses: release-drafter/release-drafter@v5
        with:
          config-name: release-drafter.yml
          disable-autolabeler: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Install cargo-edit
        run: cargo install cargo-edit --no-default-features --features set-version

      - name: Update dependency versions
        run: cargo update

      - name: Update Polars CLI version
        run: cargo set-version ${{ steps.draft.outputs.tag_name }}

      - name: Create pull request
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.DEPLOY_PAT }}
          branch: 'release/${{ steps.draft.outputs.version }}'
          title: 'build: Set version to ${{ steps.draft.outputs.tag_name }} and update dependencies'
          body: |
            #### Changes

            * Bump Polars CLI version to ${{ steps.draft.outputs.version }}
            * Update Polars to the latest commit available in the main branch
            * Update other dependencies to their latest non-breaking versions
