name: Bump version

on:
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: read

jobs:
  bump-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Draft release
        id: draft
        uses: release-drafter/release-drafter@v5
        with:
          config-name: release-drafter.yml
          disable-autolabeler: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Install cargo-edit
        run: cargo install cargo-edit --no-default-features --features set-version

      - name: Update dependency versions
        run: cargo update

      - name: Update Polars CLI version
        run: cargo set-version ${{ steps.draft.outputs.version }}

      - name: Commit to release branch
        uses: EndBug/add-and-commit@v9
        with:
          message: 'build: Set version to ${{ steps.draft.outputs.version }} and update dependencies'
          default_author: github_actions
          new_branch: release/${{ steps.draft.outputs.version }}

      - name: Create pull request
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.DEPLOY_PAT }}
          branch: release/${{ steps.draft.outputs.version }}

